---
title: "Primer acercamiento Cox Bayeisano"
output:
  pdf_document: default
  html_document: default
date: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rjags)
library(coda)
library(KMsurv)
library(dplyr)
library(tidyverse)
data(larynx) #importamos marco de datos
X <- larynx #marco de datos para definir la matriz diseño 
time <- larynx$time #definfimos un vector con las observaciónes de la variable "time"
```

```{r}
time <- larynx$time #definfimos un vector con las observaciónes de la variable "time"
K <- 3 #número de intervalo que escogemos 
X <- larynx #marco de datos 
a <- seq(0, max(larynx$time) + 0.001, length.out = K + 1) #vector de tiempos de censura 
int.obs <- matrix(data = NA, nrow = nrow(larynx), ncol = length(a) - 1)
d <- matrix(data = NA, nrow = nrow(larynx), ncol = length(a) - 1) 
for(i in 1:nrow(larynx)){
  for (k in 1:(length(a) - 1)){
    d[i, k] <- ifelse(time[i] - a[k] > 0, 1, 0) * ifelse(a[k + 1] - time[i] > 0, 1, 0)#indicadora del intervalo
    int.obs[i, k] <- d[i, k] * k #indica en que intervalo (1,2,3) cae la observación. 
  }
}
int.obs <- rowSums(int.obs) #vector que nos indica en que intervalo cae cada observación
```

```{r}
#datos con los cuales vamos a entrenar el modelo 
data.jags <- list(n = nrow(larynx), m=length(a)-1,a = a, delta=larynx$delta, time=larynx$time, X=X[,-1], 
                  int.obs=int.obs, Nbetas=ncol(X)-1, zeros=rep(0,nrow(larynx)))

#función para inicializar el modelo 
init.jags <- function(){
  list(beta = rnorm(ncol(X)-1), lambda =runif(3,0.1))
}
#parámetros que vamos a monitorear   
param.jags <-c("beta", "lambda")  #paramteros a monitorear
```


```{r}
#compilación del modelo 
modelo_compilado <- jags.model(data = data.jags,file = "modelo_prueba1.txt", inits = init.jags, n.chains = 3)
```
```{r}
update(modelo_compilado, 1000)
res <- coda.samples(modelo_compilado,variable.names=param.jags,n.iter=50000, n.thin=10)
```

