---
title: "Optimización codigo"
author: ' '
date: ' '
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Pequeña comparación entre de las eficiencias comp. 

```{r}
library(MASS)
library(tidyverse)
library(dplyr)
library(datos)
library(htmlwidgets)
library(survival)
library(AUC)
library(gdata)
library(dplyr)
library(DescTools)
library(openxlsx)
```

Segun lo panteado en "DB_preprop_Bayesianav2.Rmd"
```{r}
#cargamos la base de datos
Carga_viral <- read.csv("../DBs/lab_rna_sim.csv")
CV <- read.csv("../DBs/lab_rna_sim.csv")
#para probar el primer bucle for 
Carga_viral_1eros_4000v1 <- Carga_viral[1:4000,]
Carga_viral_1eros_4000v1$eliminar <- as.Date(NA)#columna de apoyo

#para probar el segundo bucle for 
Carga_viral_1eros_4000v2 <- Carga_viral[1:4000,]
Carga_viral_1eros_4000v2$eliminar <- as.Date(NA)#columna de apoyo

```

```{r}
for (i in 1:length(Carga_viral_1eros_4000v1$patient)) {
  reg = Carga_viral_1eros_4000v1$patient[i] #tomamos el paciente
  datos_1 = Carga_viral_1eros_4000v1 %>% filter(patient == reg) #optenemos toda la info del paciente
  datos_1$eliminar <- rep(0,length(datos_1$patient))
  datos_1$eliminar = as.Date(min(datos_1$rna_d))   # Fecha de inicio del paciente que cumple las condiciones
  Carga_viral_1eros_4000v1$eliminar[Carga_viral_1eros_4000v1$patient==reg] = datos_1$eliminar # para cada paciente hacemos coincidir una columna de minimos reptidos (los valores en datos_1$eliminar ) con los renglones de carga_viral$eliminar en los  #aparezca el paciente escogido.                      
}

```

```{r}
#ponemos NA en aquellas celdas que no son el minimo de fecha de registro de rna_d 
for (i in 1:length(Carga_viral_1eros_4000v1$patient)){ 
  if (Carga_viral_1eros_4000v1$rna_d[i] != Carga_viral_1eros_4000v1$eliminar[i]) {
    Carga_viral_1eros_4000v1$eliminar[i] = NA
  }
}
```

Segun lo planteado en el archivo "DB_preprop_Bayesianav1.Rmd"
```{r}
patients <- unique(Carga_viral_1eros_4000v2$patient) #vector con pacientes únicos 

for (i in 1:length(patients)){
  reg = patients[i] #tomamos el paciente
  datos_1 = Carga_viral_1eros_4000v2 %>% filter(patient == reg) #optenemos toda la info del paciente
  datos_1$eliminar = NA
  datos_1$eliminar = as.Date(min(datos_1$rna_d))   #Fecha de inicio del paciente que cumple las condiciones
  Carga_viral_1eros_4000v2$eliminar[Carga_viral_1eros_4000v2$patient==reg] = datos_1$eliminar # para cada paciente hacemos coincidir una columna de minimos reptidos (los valores en datos_1$eliminar ) con los renglones de carga_viral$eliminar en los  #aparezca el paciente escogido.                      
}
```

```{r}
#ponemos NA en aquellas celdas que no son el mínimo de fecha de registro de rna_d 
for (i in 1:length(patients)){ 
  if (Carga_viral_1eros_4000v2$rna_d[i] != Carga_viral_1eros_4000v2$eliminar[i]) {
    Carga_viral_1eros_4000v2$eliminar[i] = NA
  }
}
```

Comprobemos que en efecto ambos marcos de datos son igules 

```{r}
#quitamos los datos del tipo NA
v1 <- na.omit(Carga_viral_1eros_4000v2) 
v2 <- na.omit(Carga_viral_1eros_4000v2)

v1 == v2 #ambos marcos de datos son iguales 
```
%## Una intento función que sintetiza todos los casos tratados en ambas versiones del archivo .Rmd 

```{r echo=FALSE}
CV_1ros_4000 <- Carga_viral[1:4000,]
fun_fecha_min <- function(X,index,valor){
#Definiciones globales
indice = as.character(substitute(indice)) #indice lo volvemos cadenda de carac 
valor  = as.character(substitute(valor)) #valor lo volvemos cadenda de carac
eliminar = as.character(substitute(eliminar))  
 X[[eliminar]] = as.Date(NA)  #columna auxiliar
inds = unique(X[[indice]])#indices tomados de forma unica 
L = length(unique(X[[indice]]))
 for(i in 1:L){
   reg = inds[i]
   datos = X %>% filter((X[[indice]] == reg))
   datos[[eliminar]] = NA
   X[[eliminar]] = as.Date(min(datos[[valor]]))
   X[[eliminar]][X[[indice]] == reg] = datos[[eliminar]]
 }
 for(i in 1:L){
   if(X[[eliminar]][i] != datos[[eliminar]][i]){
     X[[eliminar]][i] = NA
   }
 }
 return(na.omit(X))
}
```

```{r}
CV_1ros_4000 <- Carga_viral[1:4000,]
fun_fecha_MIN <- function(X,indice,valor){
#Definiciones globales
indice = as.character(substitute(indice)) #indice lo volvemos cadenda de carac 
valor  = as.character(substitute(valor)) #valor lo volvemos cadenda de carac
eliminar = as.character(substitute(eliminar))  
 X[eliminar] = as.Date(NA)  #columna auxiliar
inds = unique(X[indice])#indices tomados de forma unica 
L = length(unique(X[indice]))
 for(i in 1:L){
   reg = inds[i]
   datos = X %>% filter_all(X[indice] == reg)
  datos[eliminar] = NA
   X[eliminar] = as.Date(min(datos[valor]))
   X[eliminar][X[indice] == reg] = datos[eliminar]
 }
 for(i in 1:L){
   if(X[eliminar][i] != datos[eliminar][i]){
     X[eliminar][i] = NA
   }
 }
 return(na.omit(X))
}
```


```{r echo=TRUE}
CV_1ros_4000_verif <- fun_fecha_min(CV_1ros_4000,patient,rna_d) 
#CV_1ros_4000_verif == v1
```


```{r}
library(zoo)
library(rlang)

CV_1ros_4000 <- Carga_viral[1:4000,]
fecha_min <- function(X,col_indice,col_valor){
#Definiciones globales
 VAL = .data[[col_valor]]
 IND = .data[[col_indice]]
 X["eliminar"] = as.Date(NA)  #columna auxiliar
inds = unique(IND)#indices tomados de forma unica 
L = length(unique(IND))
 for(i in 1:L){
   reg = inds[i]
   datos = X %>% filter(IND == reg)
   datos["eliminar"] = NA 
   X["eliminar"] = as.Date.(min(VAL))
   X["eliminar"][IND == reg] = datos["eliminar"]
 }
 for(i in 1:L){
   if(X["eliminar"][i] != datos["eliminar"][i]){
     X["eliminar"][i] = NA
   }
 }
 return(na.omit(X))
}
```

```{r}
V_1ros_4000_verif2 <- fecha_min(X=CV_1ros_4000,col_indice="patient",col_valor="rna_d")
```

